name: auto_nanny
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter_native_splash: ^2.2.19

  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700
